import type { Metadata } from "next";
import "./globals.css";

import ConditionalWrapper from "@/component/layout/ConditionalWrapper";
import { FormProvider } from "@/context/FormContext";

export const metadata: Metadata = {
  title: "TaiesRunner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConditionalWrapper>
          <FormProvider>{children}</FormProvider>
        </ConditionalWrapper>
      </body>
    </html>
  );
}
